Support for downloading custom SIASUS files
AlertaDengue/PySUS pull request #38
Opened 2021-04-18 18:37 UTC by bcbernardo

This PR implements the enhancements proposed in #15, regarding to downloads from SIASUS other than the "Produção Ambulatorial" (PA) and "Boletim de Produção Ambulatorial individualizado" (BI) files.

Some notes on the implementation:

- The document types to be downloaded are specified with the `group` parameter in the `pysus.online_data.SIA.download()` function, which tries to mimic the interface proposed in PR #31 for CNES files. However, this implementation supports this parameter being provided both as a single string (for a single type of document) or an iterable of document type codes (which are returned in the provided order).
- The defaults for the mentioned `group` and its position amongst other function arguments are intended to provide backwards-compatibility with previous implementation, so that a function call without the `group` parameter still returns a (PA, BI) tuple.
- Downloading from SIASUS is documented in README,md.

2021-04-19 11:12 UTC, fccoelho requested changes
Thanks for this PR @bcbernardo. 
Could you modifiy as well the tests for SIA to reflect the new interface?

2021-04-19 11:12 UTC, fccoelho commented on pysus/online_data/SIA.py
> +    :param groups: 2 letter document code or a list of 2 letter codes, defaults
2,3 letter document code or a list of such codes.

2021-04-19 11:12 UTC, fccoelho commented on pysus/online_data/SIA.py
>      Download SIH records for state year and month and returns dataframe
Download **SIASUS** records

2021-04-19 11:12 UTC, fccoelho commented on pysus/online_data/SIA.py
> +                'SIA does not contain files named {}'.format(gname)
We should use f-strings instead of `"".format()`
```python
f'SIA does not contain files named {gname}'
```

2021-04-19 11:12 UTC, fccoelho commented on pysus/online_data/SIA.py
> +                'SIA does not contain files named {}'.format(gname)
Please apply this change throughout the file

2021-04-30 13:20 UTC, merged

2021-05-04 18:32 UTC, bcbernardo commented
Closes #15